export const CREATE_MEETING = "CREATE_MEETING";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAILED = "CREATE_MEETING_FAILED";

export const JOIN_MEETING = "JOIN_MEETING";
export const JOIN_MEETING_SUCCESS = "JOIN_MEETING_SUCCESS";
export const JOIN_MEETING_FAILED = "JOIN_MEETING_FAILED";

export const CONNECTION_ERROR = "CONNECTION_ERROR";

export const MOVE_TO_ROOM = "MOVE_TO_ROOM";